package com.example.ftpget

import java.io.File
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneOffset
import java.util.Locale

/** Select products for the actual RINEX observation period, not by file mtime. */
object PostPppProducts {
    data class Inputs(
        val obs: File, val nav: File, val sp3: File, val clk: File,
        val bia: File, val ionex: File, val vmfLeft: File, val vmfRight: File,
        val orography: File, val atx: File
    ) {
        fun nativeArgs(output: File): Array<String> = arrayOf(
            obs.absolutePath, nav.absolutePath, sp3.absolutePath, clk.absolutePath,
            bia.absolutePath, ionex.absolutePath, vmfLeft.absolutePath,
            vmfRight.absolutePath, orography.absolutePath, atx.absolutePath,
            output.absolutePath, output.absolutePath + ".trace"
        )
    }

    private val productSpan = Regex("_(\\d{4})(\\d{3})(\\d{2})(\\d{2})_(\\d{2})D_",
        RegexOption.IGNORE_CASE)
    private val vmfName = Regex("VMF3_(\\d{8})\\.H(00|06|12|18)", RegexOption.IGNORE_CASE)
    private val whitespace = Regex("\\s+")

    private fun rinexTime(fields: List<String>, gps: Boolean): Instant {
        require(fields.size >= 6) { "RINEX 历元时间字段不完整" }
        val seconds = fields[5].toDouble()
        val second = seconds.toInt()
        val nanos = ((seconds - second) * 1e9).toInt()
        val rawYear = fields[0].toInt()
        val year = if (rawYear < 100) rawYear + (if (rawYear >= 80) 1900 else 2000)
            else rawYear
        val local = LocalDateTime.of(
            year, fields[1].toInt(), fields[2].toInt(),
            fields[3].toInt(), fields[4].toInt(), second, nanos
        )
        // RINEX generated by this app labels epochs GPS; 18 s is the
        // current GPST-UTC offset. A UTC-labelled external file stays UTC.
        return local.toInstant(ZoneOffset.UTC).minusSeconds(if (gps) 18 else 0)
    }

    private fun observationPeriod(obs: File): Pair<Instant, Instant> {
        var first: Instant? = null
        var last: Instant? = null
        var gps = true
        var inHeader = true
        obs.bufferedReader().useLines { lines ->
            for (line in lines) {
                if (inHeader) {
                    if (line.contains("TIME OF FIRST OBS")) {
                        val prefix = line.take(60).trim().split(whitespace)
                        gps = !prefix.any { it.equals("UTC", ignoreCase = true) }
                        first = rinexTime(prefix, gps)
                    }
                    if (line.contains("END OF HEADER")) inHeader = false
                } else if (line.startsWith(">")) {
                    val fields = line.drop(1).trim().split(whitespace)
                    if (fields.size >= 6) last = rinexTime(fields, gps)
                }
            }
        }
        val start = first ?: throw IllegalArgumentException("RINEX 缺少 TIME OF FIRST OBS：${obs.name}")
        val end = last ?: start
        require(!end.isBefore(start)) { "RINEX 历元时间逆序：${obs.name}" }
        return start to end
    }

    private fun productPeriod(name: String): Pair<Instant, Instant>? {
        val match = productSpan.find(name) ?: return null
        val day = LocalDateTime.of(match.groupValues[1].toInt(), 1, 1, 0, 0)
            .plusDays(match.groupValues[2].toLong() - 1L)
            .plusHours(match.groupValues[3].toLong())
            .plusMinutes(match.groupValues[4].toLong())
        val start = day.toInstant(ZoneOffset.UTC)
        return start to start.plusSeconds(match.groupValues[5].toLong() * 86400L)
    }

    private fun choose(
        files: List<File>, label: String, first: Instant, last: Instant,
        matches: (String) -> Boolean
    ): File {
        return files.filter { matches(it.name.uppercase(Locale.US)) }
            .mapNotNull { file -> productPeriod(file.name)?.let { file to it } }
            .filter { (_, period) ->
                !period.first.isAfter(first) && !period.second.isBefore(last)
            }
            .maxByOrNull { it.second.first }?.first
            ?: throw IllegalArgumentException("缺少覆盖观测时段的 $label 产品")
    }

    private fun unpack(file: File): File {
        if (!file.name.endsWith(".gz", ignoreCase = true)) return file
        require(FtpDownloader.reusableLocalFile(file)) { "压缩产品损坏：${file.name}" }
        val target = File(file.parentFile, file.name.dropLast(3))
        if (!target.isFile || target.length() == 0L || target.lastModified() < file.lastModified()) {
            require(FileUtil.unGzip(file, target) && target.length() > 0L) {
                "解压失败：${file.name}"
            }
        }
        return target
    }

    fun resolve(dir: File): Inputs {
        val files = dir.listFiles()?.filter { it.isFile && it.length() > 0L }.orEmpty()
        val obs = files.filter { file ->
            val name = file.name.uppercase(Locale.US)
            name.endsWith("_MO.RNX") || Regex("\\.\\d{2}O$").containsMatchIn(name)
        }.maxByOrNull { it.lastModified() }
            ?: throw IllegalArgumentException("缺少 RINEX OBS（不能使用 NAV 代替）")
        val (first, last) = observationPeriod(obs)
        val nav = choose(files, "NAV", first, last) { it.endsWith("_MN.RNX") || it.endsWith("_MN.RNX.GZ") }
        val sp3 = choose(files, "SP3", first, last) { it.endsWith("_ORB.SP3") || it.endsWith("_ORB.SP3.GZ") }
        val clk = choose(files, "CLK", first, last) { it.endsWith("_CLK.CLK") || it.endsWith("_CLK.CLK.GZ") }
        val bia = choose(files, "BIA", first, last) { it.endsWith("_OSB.BIA") || it.endsWith("_OSB.BIA.GZ") }
        val ionex = choose(files, "IONEX", first, last) { it.endsWith("_GIM.INX") || it.endsWith("_GIM.INX.GZ") }

        val grids = files.mapNotNull { file ->
            val match = vmfName.matchEntire(file.name) ?: return@mapNotNull null
            val date = match.groupValues[1]
            val y = date.substring(0, 4).toInt()
            val m = date.substring(4, 6).toInt()
            val d = date.substring(6, 8).toInt()
            val hour = match.groupValues[2].toInt()
            if (!FtpDownloader.reusableVmf3File(file, y, m, d, hour)) return@mapNotNull null
            LocalDateTime.of(y, m, d, hour, 0).toInstant(ZoneOffset.UTC) to file
        }.sortedBy { it.first }
        val left = grids.lastOrNull { !it.first.isAfter(first) }
        val right = grids.firstOrNull { it.first.isAfter(first) }
        require(left != null && right != null && !right.first.isBefore(last)) {
            "缺少覆盖整段观测的相邻两期 VMF3；当前后处理每次只加载一对格网"
        }
        val orog = File(dir, "orography_ell_5x5")
        val atx = File(dir, "igs20.atx")
        require(BundledProducts.ready(orog) && BundledProducts.ready(atx)) {
            "ATX 或 VMF3 格网点椭球高文件缺失"
        }
        return Inputs(obs, unpack(nav), unpack(sp3), unpack(clk), unpack(bia),
            unpack(ionex), left.second, right.second, orog, atx)
    }
}
