# Every Android core source must match the recorded PC snapshot.
# For local development -DPPP_PC_SOURCE_DIR=/path/to/PC/src also detects PC drift.
file(STRINGS "${PPP_LIVE_DIR}/pc_profile.sha256" profile_records)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${PPP_LIVE_DIR}/pc_profile.sha256")
set(verified_names "")
string(ASCII 239 187 191 utf8_bom)
foreach(record IN LISTS profile_records)
    if(record MATCHES "^([0-9a-f]+) ([A-Za-z0-9_.]+)$")
        set(expected "${CMAKE_MATCH_1}")
        set(name "${CMAKE_MATCH_2}")
        list(FIND verified_names "${name}" duplicate_index)
        if(NOT duplicate_index EQUAL -1)
            message(FATAL_ERROR "Duplicate PPP manifest record: ${name}")
        endif()
        list(APPEND verified_names "${name}")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            "${PPP_LIVE_DIR}/${name}")
        file(READ "${PPP_LIVE_DIR}/${name}" contents)
        string(REGEX REPLACE "^${utf8_bom}" "" contents "${contents}")
        string(REPLACE "\r\n" "\n" contents "${contents}")
        string(REGEX REPLACE "[\r\n]+$" "" contents "${contents}")
        string(SHA256 actual "${contents}")
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "PPP PC snapshot mismatch: ${name}. Verify/sync with sync_smartphone_ppp.ps1.")
        endif()
        if(DEFINED PPP_PC_SOURCE_DIR AND NOT PPP_PC_SOURCE_DIR STREQUAL "")
            file(READ "${PPP_PC_SOURCE_DIR}/${name}" pc_contents)
            string(REGEX REPLACE "^${utf8_bom}" "" pc_contents "${pc_contents}")
            string(REPLACE "\r\n" "\n" pc_contents "${pc_contents}")
            string(REGEX REPLACE "[\r\n]+$" "" pc_contents "${pc_contents}")
            string(SHA256 pc_actual "${pc_contents}")
            if(NOT pc_actual STREQUAL expected)
                message(FATAL_ERROR "PC/Android PPP drift: ${name}. Refresh the Android snapshot.")
            endif()
        endif()
    endif()
endforeach()
list(LENGTH verified_names verified_count)
if(NOT verified_count EQUAL 29)
    message(FATAL_ERROR "Incomplete PPP snapshot manifest: ${verified_count} records, expected 29")
endif()
message(STATUS "Verified PC smartphone PPP snapshot (NFREQ=4, ENAGLO, no ENAQZS)")
